### 변수 설정
@pointId = 1

### point 조회
GET {{host}}/point/{{pointId}}

### point 내역 조회
GET {{host}}/point/{{pointId}}/histories

### point 충전
PATCH {{host}}/point/{{pointId}}//charge
Content-Type: application/json

{
  "amount": 1000
}

### point 사용
PATCH {{host}}/point/{{pointId}}//use
Content-Type: application/json

{
  "amount": 500
}